#!/usr/bin/env python

from sys import argv
import calcm # calc module

help_prompt = f'''
 Usage: {argv[0]} '2 + 2'

 Use spaces to separate operators from operands (optional for parentheses)

 You can divide you expression in blocks if it's too big:

   $ {argv[0]} '2 + 2 \\'
   $ ...* 2
   $ 6 

 Note that you can have multiple slashes in your expression:

   $ {argv[0]} '2 + 2 \\ \\'
   $ ...*
   $ ...2
   $ 6 

'''

if len(argv) == 1 or argv[1] == 'help' or argv[1] == '--help' or argv[1] == '-h':
    exit(help_prompt)

elif argv[1][-1] == '\\':

    slashes = argv[1].count('\\')

    for _ in range(0, slashes):
        extra_exp = input('...')
        argv[1] = argv[1].replace('\\', extra_exp, 1)


exp = calcm.lexer(argv[1])

exp = calcm.calc(exp)

if exp == int(exp):
    print(int(exp))
else:
    print(exp)